# infra/k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
  annotations:
    kubernetes.io/ingress.class: "traefik" # or nginx if using nginx-ingress
spec:
  rules:
  - host: myapp.example.com   # replace with your domain or use server IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-register
            port: { number: 80 }
  - host: api.myapp.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port: { number: 8080 }
